package framework;

import java.util.Map;

/*
 *                                                          *
 **                 DO NOT EDIT THIS FILE                  **
 ***         YOU DO NOT HAVE TO LOOK IN THIS FILE         ***
 **** IF YOU HAVE QUESTIONS PLEASE DO ASK A TA FOR HELP  ****
 *****                                                  *****
 ************************************************************
 */

/**
 * Describes the interface used for routing protocols
 *
 * @author Jaco ter Braak & Frans van Dijk, University of Twente.
 * @version 12-03-2019
 */
public interface IRoutingProtocol {

    /**
     * This method is called by the framework before the simulation starts. The
     * protocol implementation should be initialized here.
     *
     * @param linkLayer
     */
    void init(LinkLayer linkLayer);

    /**
     * This method is called by the framework each 'tick'.
     *
     * @param packetsWithLinkCosts
     */
    void tick(PacketWithLinkCost[] packetsWithLinkCosts);

    /**
     * The method is called by the framework  during and after the simulation, to
     * retrieve the local forwarding table.
     * The keys in the table are the destinations and the values should be the next hop.
     *
     * @return ForwardingTable
     */
    Map<Integer, Integer> getForwardingTable();
}
