package framework;

/*
 *                                                          *
 **                 DO NOT EDIT THIS FILE                  **
 ***         YOU DO NOT HAVE TO LOOK IN THIS FILE         ***
 **** IF YOU HAVE QUESTIONS PLEASE DO ASK A TA FOR HELP  ****
 *****                                                  *****
 ************************************************************
 */

/**
 * Link layer interface, used for clarity
 *
 * @author Jaco ter Braak & Frans van Dijk, University of Twente.
 * @version 12-03-2019
 */
public class LinkLayer {
    private RoutingChallengeClient client;

    public LinkLayer(RoutingChallengeClient client) {
        this.client = client;
    }

    /**
     * Gets the address within the network, associated with this interface
     *
     * @return address
     */
    public int getOwnAddress() {
        return client.getAddress();
    }

    /**
     * Transmits a packet
     *
     * @param packet the packet to transmit
     */
    public void transmit(Packet packet) {
        client.Transmit(packet);
    }
}
