package framework;

/*
 *                                                          *
 **                 DO NOT EDIT THIS FILE                  **
 ***         YOU DO NOT HAVE TO LOOK IN THIS FILE         ***
 **** IF YOU HAVE QUESTIONS PLEASE DO ASK A TA FOR HELP  ****
 *****                                                  *****
 ************************************************************
 */

/**
 * Specifies a data transfer protocol.
 *
 * @author Jaco ter Braak & Frans van Dijk, University of Twente.
 * @version 10-02-2016
 */
public abstract class IRDTProtocol implements ITimeoutEventHandler {

    private NetworkLayer networkLayer;
    private int fileID;
    
    /**
     * Run the protocol as sender. Called from the framework
     */
    public abstract void sender();

    /**
     * Run the protocol as receiver. Called from the framework
     */
    public abstract Integer[] receiver();
    
    /**
     * Sets the network layer implementation. This network layer is used for transmitting and receiving packets.
     * @param networkLayer the network layer to use for transmitting and receiving packets.
     */
    public void setNetworkLayer(NetworkLayer networkLayer) {
        this.networkLayer = networkLayer;
    }

    /**
     * Gets the network layer implementation to use for transmitting and receiving packets.
     * @return the network layer implementation to use for transmitting and receiving packets.
     */
    protected NetworkLayer getNetworkLayer() {
        return networkLayer;
    }

    /**
     * Sets the ID of the file to send/receive.
     * @param fileID the ID of the file to send/receive.
     */
    public void setFileID(int fileID) {
        this.fileID = fileID;
    }

    /**
     * @return the ID of the file to send/receive.
     */
    public int getFileID() {
        return fileID;
    }
}
