package framework;

/*
 *                                                          *
 **                 DO NOT EDIT THIS FILE                  **
 ***         YOU DO NOT HAVE TO LOOK IN THIS FILE         ***
 **** IF YOU HAVE QUESTIONS PLEASE DO ASK A TA FOR HELP  ****
 *****                                                  *****
 ************************************************************
 */

/**
 * Interface for timeout event handlers.
 * 
 * @author Jaco ter Braak, University of Twente.
 * @version 11-01-2014
 */
public interface ITimeoutEventHandler {
    /**
     * Is triggered when the timeout has elapsed
     */
    void TimeoutElapsed(Object tag);
}
